os:
#- linux
- osx
osx_image: xcode9.2
sudo: required
dist: trusty
group: travis_latest
language: c++
compiler:
- clang
- gcc
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: build/dist
  on:
    branch: master
    condition: "($CC = clang) && ($TRAVIS_OS_NAME = osx)"
before_install:
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    sudo apt-get update -qq;
    sudo apt-get install -y build-essential;
    sudo apt-get install -y qtbase5-dev;
    sudo apt-get install -y libqt5svg5-dev;
    sudo apt-get install -y ninja-build;
  elif [ "$TRAVIS_OS_NAME" == "osx" ]; then
    brew update > /dev/null;
    brew install ninja;
    brew install qt5;
    export PATH=/usr/local/opt/qt/bin:$PATH;
  fi
cache:
  directories:
    - $HOME/Library/Caches/Homebrew
script:
- mkdir build
- cd build
- cmake -G Ninja ..
- ninja -v || exit 1
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    cpack;
    mkdir dist; mv *.dmg dist;
  fi
