os:
- linux
- osx
osx_image: xcode9.1
sudo: required
dist: trusty
language: c++
compiler:
- clang
- gcc
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: dist
  on:
    branch: master
    condition: "($CC = clang) && ($TRAVIS_OS_NAME = osx)"
before_install:
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    sudo apt-get update -qq;
    sudo apt-get install -y build-essential;
    sudo apt-get install -y qtbase5-dev;
    sudo apt-get install -y ninja-build;
  elif [ "$TRAVIS_OS_NAME" == "osx" ]; then
    brew update > /dev/null;
    brew install ninja;
    brew install qt5;
    brew install tree;
    export PATH=/usr/local/opt/qt/bin:$PATH;
  fi
script:
- mkdir build
- cd libmobi ; patch -p1 < ../libmobi.patch; cd ..
- cd build
- cmake -G Ninja ..
- ninja || exit 1
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    /usr/local/opt/qt/bin/macdeployqt mobidict.app;
    tree mobidict.app;
    hdiutil create mobidict.dmg -volname "Mobidict" -fs HFS+ -srcfolder "mobidict.app";
    mkdir dist; mv mobidict.dmg dist;
  fi
