version: '1.3.r{build}'

image: Visual Studio 2017

artifacts:
- path: 'build/*-win64.exe'
  name: Mobidict

build:
     verbosity: detailed

cache:
    c:\tools\ -> appveyor.yml

init:
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

on_finish:
- ps: $blockRdp = $false; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
- cmd: >-
    cd c:\tools\vcpkg

    git pull

    .\bootstrap-vcpkg.bat

    mkdir C:\projects\deps

    cd C:\projects\deps

    set NINJA_URL="https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-win.zip"

    appveyor DownloadFile %NINJA_URL% -FileName ninja.zip

    7z x ninja.zip -oC:\projects\deps\ninja > nul

    set PATH=C:\projects\deps\ninja;%PATH%

    vcpkg install zlib:x64-windows-static

    appveyor DownloadFile http://prereleases.llvm.org/win-snapshots/LLVM-8.0.0-r347735-win64.exe -FileName llvm-installer.exe

    START /WAIT llvm-installer.exe /S /D=C:\"Program Files\LLVM"

    clang-cl --version

    ninja --version
    
    cmake --version

before_build:
- cmd: >-
    call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"

build_script:
- cmd: >-
    cd C:\projects\mobidict

    git submodule init

    git submodule update

    mkdir build

    cd build

    set PATH=C:\Qt\5.11\msvc2017_64\bin;%PATH%

    cmake -G Ninja -DCMAKE_C_COMPILER=clang-cl -DCMAKE_CXX_COMPILER=clang-cl -DCMAKE_BUILD_TYPE=RelWithDebInfo -DVCPKG_TARGET_TRIPLET=x64-windows-static -DCMAKE_TOOLCHAIN_FILE=C:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake ..

    ninja

    set PATH=C:\Program Files (x86)\NSIS\bin%PATH%

    cpack
