version: '{build}'

image: Visual Studio 2017

build:
     verbosity: detailed

install:
- cmd: >-
    mkdir C:\projects\deps

    cd C:\projects\deps

    set NINJA_URL="https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-win.zip"

    appveyor DownloadFile %NINJA_URL% -FileName ninja.zip

    7z x ninja.zip -oC:\projects\deps\ninja > nul

    set PATH=C:\projects\deps\ninja;%PATH%

    ninja --version
    
    cmake --version

before_build:
- cmd: >-
    call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"

build_script:
- cmd: >-
    cd C:\projects\mobidict

    git submodule init

    git submodule update

    mkdir build

    cd build

    dir C:\cygwin64\bin

    set PATH=C:\Qt\5.9.1\msvc2017_64\bin;%PATH%

    cmake -G Ninja -DCMAKE_BUILD_TYPE=RelWithDebInfo ..

    ninja

