version: '1.1-beta{build}'

image: Visual Studio 2017

build:
     verbosity: detailed

install:
- cmd: >-
    mkdir C:\projects\deps

    cd C:\projects\deps

    set NINJA_URL="https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-win.zip"

    appveyor DownloadFile %NINJA_URL% -FileName ninja.zip

    7z x ninja.zip -oC:\projects\deps\ninja > nul

    set PATH=C:\projects\deps\ninja;%PATH%

    set PATCH_URL="https://downloads.sourceforge.net/project/gnuwin32/patch/2.5.9-7/patch-2.5.9-7-bin.zip"

    appveyor DownloadFile %PATCH_URL% -FileName patch.zip

    7z x patch.zip -oC:\projects\deps\patch > nul

    set PATH=C:\projects\deps\patch\bin;%PATH%

    patch --version

    ninja --version
    
    cmake --version

before_build:
- cmd: >-
    call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"

build_script:
- cmd: >-
    cd C:\projects\mobidict

    git submodule init

    git submodule update

    cd libmobi

    patch -p1 --binary < C:\projects\mobidict\libmobi.patch

    patch -p1 --binary < C:\projects\mobidict\update-enc-length.patch

    cd ..

    mkdir build

    cd build

    set PATH=C:\Qt\5.9\msvc2017_64\bin;%PATH%

    cmake -G Ninja -DCMAKE_BUILD_TYPE=RelWithDebInfo ..

    ninja

    set PATH=C:\Program Files (x86)\NSIS\bin%PATH%

    cpack -V
